spmPRYFasttasty/spmPRYFasttasty/Controllers/spmClsIngredienteController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using spmPRYFasttasty.Models;

namespace spmPRYFasttasty.Controllers
{
    public class spmClsIngredienteController : Controller
    {
        // GET: spmClsIngrediente
        private spmINGtIngrediente objIngrediente = new spmINGtIngrediente();

        // GET: spmClsPadecimientoSalud
        public ActionResult Index()
        {

            return View(objIngrediente.Listar());
        }

        [HttpPost]
        public ActionResult listado()
        {

            return Json(new { data= objIngrediente.ListarRecetas() });
        }

        //Accion AgregarEditar
        public ActionResult AgregarEditar(int id = 0)
        {
            return View(
                id == 0 ? new spmINGtIngrediente() //Agregar un nuevo objeto     (Si id es igual a cero es igual a SI entonces crea un objeto Usuario())
                : objIngrediente.Obtener(id) //DEvuelve un objeto
            );
        }

        //Accion Guardar
        [HttpPost]
        public ActionResult Guardar(spmINGtIngrediente objIngrediente, HttpPostedFileBase foto)
        {
            if (foto != null && foto.ContentLength > 0)
            {
                string fileName = Path.GetFileName(foto.FileName);
                string fileLocationString = "~/IngredientesFotos";
                string fileLocation = Path.Combine(Server.MapPath(fileLocationString), fileName);
                if (!Directory.Exists(Server.MapPath(fileLocationString))) Directory.CreateDirectory(Server.MapPath(fileLocationString));
                foto.SaveAs(fileLocation);
                objIngrediente.INGfoto = fileName;
            }
            objIngrediente.Guardar();
            return Redirect("~/spmClsIngrediente/Index");
        }

        //AccionEliminar
        public ActionResult Eliminar(int id)
        {
            objIngrediente.INGid = id;
            objIngrediente.Eliminar();
            return Redirect("~/spmClsIngrediente");
        }


    }
}

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsIngrediente/AgregarEditar.cshtml
@model spmPRYFasttasty.Models.spmINGtIngrediente
@{
    ViewBag.Title = "AgregarEditar";
}
<center><h2>Registrar Ingrediente</h2></center>
<br />
@using (Html.BeginForm("Guardar", "spmClsIngrediente", FormMethod.Post, new { id = "frm-ingrediente" }))
{
    @Html.HiddenFor(x => x.INGid)
    <div class="form-group row">
        <div class="form-group">
            @Html.Label("ID: ")
            @Html.TextBoxFor(x => x.INGid, new { @class = "form-control", disabled = true })
        </div>
        <div class="form-group">
            @Html.Label("NOMBRE: ")
            @Html.TextBoxFor(x => x.INGnombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.INGnombre, null, new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.Label("UNIDAD: ")
            @Html.TextBoxFor(x => x.INGunidad_medida, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.INGunidad_medida, null, new { @class = "text-danger" })
        </div>
        @*<div class="form-group">
                @Html.Label("FOTO REFERENCIAL:")
                <input type="file" name="foto" class="form-control" />
            </div>*@
        <div class="form-group">
            @Html.Label("FOTO REFERENCIAL: ")
            @Html.TextBoxFor(x => x.INGfoto, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.INGfoto, null, new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Guardar</button>
        @*<a href="~/spmClsIngrediente" class="btn btn-danger">Cancelar</a>*@
    </div>
}

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsIngrediente/Index.cshtml
@model List<spmPRYFasttasty.Models.spmINGtIngrediente>
@{
    ViewBag.Title = "Index";
    //Layout = null;
}
<body>
    <!-- about-top -->
        <div class="container">
            <h2 class="tittle-w3"> GESTIONAR  <span>    INGREDIENTES </span></h2>
            <div class="about-section">
                <!-- special -->
                <div class="special">
                    <div class="container">
                        <div class="text-right">
                            <a href="~/spmClsIngrediente/AgregarEditar/" class="btn btn-warning text-right"><h7>Registrar Ingrediente</h7></a>
                        </div>
                        <br />
                        <div class="text-left" style="font:bold">
                            <h2>Ingredientes Registrados</h2></a>
                        </div>
                        <br />
                        <div class="main-search-box pt-3 pb-4 d-inline-block navbar-right ">
                            <form class="form-inline search-form justify-content-center" action="" method="get">
                                <input type="text" name="search" class="form-control search-input" style="width:300px">
                                <button type="button" class="btn search-btn" value="Search"><i class="glyphicon glyphicon-search"></i></button>
                            </form>
                        </div>
                        <br />
                        <div class="p_recype_item_main">
                            <div class="row p_recype_item_active">
                                @foreach (var u in Model)
                                {
                                    <div class="col-md-4 col-sm-6 break snacks">
                                        <div class="feature_item">
                                            <div class="feature_item_inner">
                                                <div id="mycarousel" class="carousel slide" data-ride="carousel">
                                                    <div class="carousel-inner">
                                                        <div class="item active">
                                                            <img src="~/IngredientesFotos/@u.INGfoto" alt="" class="img-responsive" style="height:250px;width:350px">
                                                            @*<div class="carousel-caption">
                                                                    <div class="form-group">
                                                                        <center><h3 class="title">@u.INGnombre </h3></center>
                                                                    </div>
                                                                </div>*@
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <center><h3 class="title">@u.INGnombre</h3></center>
                                            <br />
                                            <div class="pad-ver" style="align-content:center!important;">
                                                <th style="align-content:center;">
                                                    <a class="btn btn-secondary btn-lg" type="button" style="width:40px" href="~/spmClsIngrediente/AgregarEditar/@u.INGid" title="Editar"><i class="glyphicon glyphicon-edit"></i></a>
                                                    <a class="btn btn-secondary btn-lg" type="button" style="width:40px" href="~/spmClsIngrediente/Eliminar/@u.INGid" title="Eliminar"
                                                       onclick="return confirm('¿Esta seguro de eliminar este ingrediente?' @u.INGid);"><i class="glyphicon glyphicon-trash"></i></a>
                                                </th>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>
                <!-- //special -->
            </div>
        </div>

</body>