spmPRYFasttasty/spmPRYFasttasty/Controllers/spmClsRecetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using spmPRYFasttasty.Models;
using System.IO;
namespace spmPRYFasttasty.Controllers
{
    public class spmClsRecetaController : Controller
    {
        private spmRINpReceta_Ingrediente objRecetaIngre = new spmRINpReceta_Ingrediente();
        private spmINGtIngrediente objIngrediente = new spmINGtIngrediente();

        private spmRECpReceta objReceta = new spmRECpReceta();
        private spmPADtPadecimiento_Salud objSalud = new spmPADtPadecimiento_Salud();
        private spmUSUtUsuario objUsuario = new spmUSUtUsuario();
        // GET: spmClsReceta
       
        public ActionResult FrmRecetaPrincipal()
        {
            return View(objReceta.Listar());
        }

        public ActionResult FrmRecetaAgregarEditar(int id = 0)
        {
            ViewBag.spmRECpReceta = objReceta.Listar();
            ViewBag.spmPADtPadecimiento_Salud = objSalud.Listar();
            ViewBag.spmUSUtUsuario = objUsuario.Listar();
            return View(

                 id == 0 ? new spmRECpReceta()
                 : objReceta.Obtener(id)
                 );
        }
        public ActionResult RecetaIngrediente(int id = 0)
        {
            ViewBag.spmRECpReceta = objReceta.Listar();
            ViewBag.spmRINpReceta_Ingrediente = objRecetaIngre.Listar();
            ViewBag.spmINGtIngrediente = objIngrediente.Listar();
            return View(
                id == 0 ? new spmRINpReceta_Ingrediente()
                : objRecetaIngre.Obtener(id)
                );
        }
        public ActionResult FrmRecetaIngrediente(int id = 0)
        {
            ViewBag.spmRECpReceta = objReceta.Listar();
            ViewBag.spmRINpReceta_Ingrediente = objRecetaIngre.Listar();
            ViewBag.spmINGtIngrediente = objIngrediente.Listar();
            return View(
                id == 0 ? new spmRINpReceta_Ingrediente()
                : objRecetaIngre.Obtener(id)
                );
        }

        public ActionResult GuardarREC(spmRINpReceta_Ingrediente objRecetaIngre)
        {

            if (ModelState.IsValid)
            {
                objRecetaIngre.Guardar();
                return Redirect("~/spmClsReceta/FrmRecetaIngrediente");
            }
            else
            {
                return View("~/spmClsReceta/FrmRecetaIngrediente");

            }
        }

        //Accion Guardar
        [HttpPost]
        public ActionResult Guardar(spmRECpReceta objReceta, HttpPostedFileBase RECfoto)
        {
            if (RECfoto != null && RECfoto.ContentLength > 0)
            {
                string fileName = Path.GetFileName(RECfoto.FileName);
                string fileLocationString = "~/Imagenes/Recetas";
                string fileLocation = Path.Combine(Server.MapPath(fileLocationString), fileName);
                if (!Directory.Exists(Server.MapPath(fileLocationString))) Directory.CreateDirectory(Server.MapPath(fileLocationString));
                RECfoto.SaveAs(fileLocation);
                objReceta.RECfoto = fileName;
            }
            objReceta.Guardar();
            return Redirect("~/spmClsReceta/FrmRecetaPrincipal");
        }
        

        //AccionEliminar
        public ActionResult EliminarREC(int id)
        {
            objRecetaIngre.RINid = id;
            objRecetaIngre.Eliminar();
            return Redirect("~/spmClsReceta/FrmRecetaIngrediente");
        }
        //AccionEliminar
        public ActionResult Eliminar(int id)
        {
            objReceta.RECid = id;
            objReceta.Eliminar();
            return Redirect("~/spmClsReceta/FrmRecetaPrincipal");
        }
    }
}

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsReceta/FrmRecetaAgregarEditar.cshtml
@model spmPRYFasttasty.Models.spmRECpReceta

@{
    List<spmPRYFasttasty.Models.spmRECpReceta> receta = ViewBag.spmRECpReceta;
    List<spmPRYFasttasty.Models.spmPADtPadecimiento_Salud> salud = ViewBag.spmPADtPadecimiento_Salud;
    List<spmPRYFasttasty.Models.spmUSUtUsuario> usuario = ViewBag.spmUSUtUsuario;

    ViewBag.Title = "Index";
}

<section class="info py-5 px-lg-5">

    <h3 class="tittle-w3"><span>Registrar </span>Receta</h3>


    <div class="container contact-form mx-auto text-lg-center " float="center">

        @using (Html.BeginForm("Guardar", "spmClsReceta", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.RECid)

            <div class="form-group row">
                <label for="inputPassword" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Nombre de la Receta</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.RECnombre, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RECnombre, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">tipo plato:</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.RECtipo_plato, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RECtipo_plato, null, new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">tiempo estimado de preparacion:</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.RECtiempo_preparacion, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RECtiempo_preparacion, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">foto referencial</label>
                <div class="col-sm-10">
                    <input type="file" name="RECfoto" id="file" class="form-control" required />
                    

                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Recomendacion para la salud</label>
                <div class="col-sm-10">
                    <select name="PADid" class="form-control">
                        <option @(Model.PADid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                        @foreach (var d in salud)
                        {
                            <option @(Model.PADid.Equals(d.PADid) ? "selected" : "") value="@d.PADid">@d.PADnombre</option>
                        }
                    </select>

                    @Html.ValidationMessageFor(x => x.PADid, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">procedimiento:</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.RECprocedimiento_preparacion, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RECprocedimiento_preparacion, null, new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Usuarios</label>
                <div class="col-sm-10">
                    <select name="USUid" class="form-control">
                        <option @(Model.USUid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                        @foreach (var d in usuario)
                        {
                            <option @(Model.USUid.Equals(d.USUid) ? "selected" : "") value="@d.USUid">@d.USUnombre, @d.USUapellido</option>
                        }
                    </select>

                    @Html.ValidationMessageFor(x => x.USUid, null, new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group mx-auto mt-3">
                <button type="submit" class="btn btn-default morebtn more black con-submit"> <span class="fa fa-save" aria-hidden="true"></span><b> Registrar</b></button>

            </div>

        }

     </div>



</section>

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsReceta/FrmRecetaIngrediente.cshtml
@model spmPRYFasttasty.Models.spmRINpReceta_Ingrediente

@{
    List<spmPRYFasttasty.Models.spmRECpReceta> receta = ViewBag.spmRECpReceta;
    List<spmPRYFasttasty.Models.spmINGtIngrediente> ingrediente = ViewBag.spmINGtIngrediente;
    List<spmPRYFasttasty.Models.spmRINpReceta_Ingrediente> receta_Ingredientes = ViewBag.spmRINpReceta_Ingrediente;

}
<body>
    <h3 class="tittle-w3"><span>Añadir </span>Ingrediente</h3>

    <section class="info py-5 px-lg-5">
        <div class="content-w3ls-inn px-lg-5">
            <div class="container py-md-5 py-3">
                <div class="px-lg-5">
                    <br />
                    <br />
                    <div class="container contact-form mx-auto text-lg-center " float="center">

                        @using (Html.BeginForm("GuardarREC", "spmClsReceta", FormMethod.Post, new { id = "frm-RecetaING" }))
                        {
                            @Html.HiddenFor(x => x.RINid)

                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Receta</label>
                                <div class="col-sm-10">
                                    <select name="RECid" class="form-control">
                                        <option @(Model.RECid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                                        @foreach (var d in receta)
                                        {
                                            <option @(Model.RECid.Equals(d.RECid) ? "selected" : "") value="@d.RECid">@d.RECnombre</option>
                                        }
                                    </select>

                                    @Html.ValidationMessageFor(x => x.RECid, null, new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Ingrediente</label>
                                <div class="col-sm-10">
                                    <select name="INGid" class="form-control">
                                        <option @(Model.INGid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                                        @foreach (var d in ingrediente)
                                        {
                                            <option @(Model.INGid.Equals(d.INGid) ? "selected" : "") value="@d.INGid">@d.INGnombre /  @d.INGunidad_medida</option>
                                        }
                                    </select>

                                    @Html.ValidationMessageFor(x => x.INGid, null, new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">cantidad</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(x => x.RINcantidad_ingrediente, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.RINcantidad_ingrediente, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group mx-auto mt-3">
                                <button type="submit" class="btn btn-default morebtn more black con-submit"> <span class="fa fa-save" aria-hidden="true"></span><b> Registrar</b></button>

                            </div>

                        }

                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th style="width:50px">ID</th>
                                    <th style="width:50px">Nombre de la receta</th>
                                    <th style="width:50px">Ingrediente</th>
                                    <th style="width:50px">Cantidad</th>
                                    

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var u in receta_Ingredientes)
                                {
                                    <tr>
                                        <th>@(u.RINid)</th>
                                        <th>@(u.spmRECpReceta.RECnombre)</th>
                                        <th>@(u.spmINGtIngrediente.INGnombre)</th>
                                        <th>@(u.RINcantidad_ingrediente)</th>

                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </div>
    </section>


</body>

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsReceta/FrmRecetaPrincipal.cshtml
@model List<spmPRYFasttasty.Models.spmRECpReceta>
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="~/Contenido/css/lightbox.css">

</head>
<body>

    <!-- //banner -->
    <!-- gallery -->
    <div class="gallery">
        <div class="container">
            <h3 class="tittle-w3"><span>Gestionar </span>Receta</h3>
            <br />
            <br />
            <div class="text-right">
                <a href="~/spmClsReceta/FrmRecetaAgregarEditar/" class="btn btn-warning text-right"><h7>Registrar Receta</h7></a>
            </div>
            <br />
            <div class="text-right">
                <a href="~/spmClsReceta/FrmRecetaIngrediente/" class="btn btn-warning text-right"><h7>Añadir Ingredientes</h7></a>
            </div>


            <div class="gallery-grids">
                @foreach (var u in Model)
                {
                    <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                        <div class="grid">
                            <figure class="effect-apollo">
                                <a class="example-image-link" href="/Imagenes/Recetas/@u.RECfoto" data-lightbox="example-set" data-title="">
                                    <img src="/Imagenes/Recetas/@u.RECfoto" alt="" style="width:350px;height:300px" />
                                    <figcaption>
                                        <h3>@u.spmPADtPadecimiento_Salud.PADnombre</h3>
                                        <p>@u.RECnombre<br>@u.RECtipo_plato</p>
                                    </figcaption>
                                </a>
                            </figure>
                            <a class="btn btn-secondary btn-lg" type="button" style="width:40px" href="~/spmClsReceta/FrmRecetaAgregarEditar/@u.RECid" title="Editar"><i class="glyphicon glyphicon-edit"></i></a>
                            <br />
                            <a class="btn btn-secondary btn-lg" type="button" style="width:40px" href="~/spmClsReceta/Eliminar/@u.RECid" title="Eliminar"
                               onclick="return confirm('¿Esta seguro de eliminar este ingrediente?' @u.RECid);"><i class="glyphicon glyphicon-trash"></i></a>

                        </div>
                    </div>
                }
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>

    <script src="~/Contenido/js/lightbox-plus-jquery.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
</body>
</html>

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsReceta/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

spmPRYFasttasty/spmPRYFasttasty/Views/spmClsReceta/RecetaIngrediente.cshtml
@model spmPRYFasttasty.Models.spmRINpReceta_Ingrediente

@{
    List<spmPRYFasttasty.Models.spmRECpReceta> receta = ViewBag.spmRECpReceta;
    List<spmPRYFasttasty.Models.spmINGtIngrediente> ingrediente = ViewBag.spmINGtIngrediente;
    List<spmPRYFasttasty.Models.spmRINpReceta_Ingrediente> receta_Ingredientes = ViewBag.spmRINpReceta_Ingrediente;

}
<link href="~/Contenido/css/bootstrap.css" rel="stylesheet" />
<body>
    <h3 class="tittle-w3"><span>Añadir </span>Ingrediente</h3>

    <section class="info py-5 px-lg-5">
        <div class="content-w3ls-inn px-lg-5">
            <div class="container py-md-5 py-3">
                <div class="px-lg-5">
                    <br />
                    <br />
                    <div class="container contact-form mx-auto text-lg-center " float="center">

                        @using (Html.BeginForm("GuardarREC", "spmClsReceta", FormMethod.Post, new { id = "frm-RecetaING" }))
                        {
                            @Html.HiddenFor(x => x.RINid)

                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Receta</label>
                                <div class="col-sm-10">
                                    <select name="RECid" class="form-control">
                                        <option @(Model.RECid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                                        @foreach (var d in receta)
                                        {
                                            <option @(Model.RECid.Equals(d.RECid) ? "selected" : "") value="@d.RECid">@d.RECnombre</option>
                                        }
                                    </select>

                                    @Html.ValidationMessageFor(x => x.RECid, null, new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">Ingrediente</label>
                                <div class="col-sm-10">
                                    <select name="INGid" class="form-control">
                                        <option @(Model.INGid.Equals("") ? "selected" : "") value="">-Seleccione-</option>
                                        @foreach (var d in ingrediente)
                                        {
                                        <option @(Model.INGid.Equals(d.INGid) ? "selected" : "") value="@d.INGid">@d.INGnombre /  @d.INGunidad_medida</option>
                                        }
                                    </select>

                                    @Html.ValidationMessageFor(x => x.INGid, null, new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="" class="col-sm-2 col-form-label" style="font-weight:bold; text-align: left">cantidad</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(x => x.RINcantidad_ingrediente, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.RINcantidad_ingrediente, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group mx-auto mt-3">
                                <button type="submit" class="btn btn-default morebtn more black con-submit"> <span class="fa fa-save" aria-hidden="true"></span><b> Registrar</b></button>

                            </div>

                        }

                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th style="width:50px">ID</th>
                                    <th style="width:50px">Nombre de la receta</th>
                                    <th style="width:50px">Ingrediente</th>
                                    <th style="width:50px">Cantidad</th>
                                    >
                                    <th style="width:50px">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var u in receta_Ingredientes)
                                {
                                    <tr>
                                        <th>@(u.RINid)</th>
                                        <th>@(u.spmRECpReceta.RECnombre)</th>
                                        <th>@(u.spmINGtIngrediente.INGnombre)</th>
                                        <th>@(u.RINcantidad_ingrediente)</th>
                                  
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </div>
    </section>


</body>